#!/bin/sh

set -e

if [ "$1" = "remove" ]; then
	[ -f /etc/logrotate.d/rsyslog ] && mv -f /etc/logrotate.d/rsyslog /etc/logrotate.d/rsyslog.disabled
fi

if [ "$1" = "purge" ] || [ "$1" = "disappear" ]; then
	[ -f /etc/logrotate.d/rsyslog.disabled ] && rm -f /etc/logrotate.d/rsyslog.disabled
fi

if [ "$1" = "remove" ]; then
	# Cleanup sendsigs omit file to avoid false positives from piuparts
	rm -f /run/sendsigs.omit.d/rsyslog
fi

# Automatically added by dh_installinit/13.24.2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/rsyslog" ] ; then
	chmod -x "/etc/init.d/rsyslog" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d rsyslog remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/default/rsyslog 8.1905.0-4~ -- "$@"
# End automatically added section
# Automatically added by dh_systemd_enable/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'rsyslog.service' >/dev/null || true
	fi
fi
# End automatically added section

