#!/bin/sh

set -e

if [ "$1" = "install" ] && [ -n "$2" ] ; then
	[ -f /etc/logrotate.d/rsyslog.disabled ] && mv -f /etc/logrotate.d/rsyslog.disabled /etc/logrotate.d/rsyslog
fi

# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/default/rsyslog 8.1905.0-4~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/rsyslog" ] ; then
	chmod +x "/etc/init.d/rsyslog" >/dev/null || true
fi
# End automatically added section

