#!/bin/sh

set -e

# Stop the socket on remove so rsyslog is not restarted via socket activation
if [ -d /run/systemd/system ] && [ "$1" = remove ] ; then
	systemctl stop syslog.socket || true
fi

# Automatically added by dh_installinit/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/rsyslog" ] ; then
	invoke-rc.d rsyslog stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/default/rsyslog 8.1905.0-4~ -- "$@"
# End automatically added section

